#!/bin/bash

set -e

honeydPath="/usr/bin/honeyd"
novaPath="$DESTDIR/usr/bin/novad"
novaHomePath="$DESTDIR/usr/share/nova"


if [ ! -f $honeydPath ]
then
    echo "File $honeydPath does not exist. Please ensure Honeyd is installed correctly before going on."
    exit
fi

if [ ! -f $novaPath ]
then
    echo "File $novaPath does not exist. Please ensure novad was correctly installed before going on."
    exit
fi

#Set pcap permissions
setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip CAP_NET_BROADCAST+eip' $honeydPath
setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip CAP_NET_BROADCAST+eip' $novaPath

#make nova group
groupadd -f nova

#Make a honeyd log file folder that belongs to 'nobody'
chown -R nobody /var/log/honeyd

# Make sure the UI_Core library gets found
ldconfig

#restart syslog so the changes will take effect
service rsyslog restart

#reload sysctl settings.
sysctl -p /etc/sysctl.conf

chgrp -R nova $novaHomePath

if [ -x /usr/bin/update-menus ] ; then update-menus ; fi


#Add sql database
QUERY="
CREATE TABLE firstrun(
	run TIMESTAMP PRIMARY KEY
);

CREATE TABLE credentials(
	user VARCHAR(100),
	pass VARCHAR(100)
);

CREATE TABLE suspect_alerts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	suspect VARCHAR(40),
	timestamp TIMESTAMP,
	statistics INT,
	classification DOUBLE
);

CREATE TABLE statistics (
		id INTEGER PRIMARY KEY AUTOINCREMENT,

		ip_traffic_distribution DOUBLE,
		port_traffic_distribution DOUBLE,
		haystack_event_frequency DOUBLE,
		packet_size_mean DOUBLE,
		packet_size_deviation DOUBLE,
		distinct_ips DOUBLE,
		distinct_ports DOUBLE,
		packet_interval_mean DOUBLE,
		packet_interval_deviation DOUBLE,
		tcp_percent_syn DOUBLE,
		tcp_percent_fin DOUBLE,
		tcp_percent_rst DOUBLE,
		tcp_percent_synack DOUBLE,
		haystack_percent_contacted DOUBLE
);"

dbFilePath="$DESTDIR/usr/share/nova/database.db"

if [[ $1 == "reset" ]]; then
	echo "You chose the reset option. This will clear all database data!"
	rm -fr $dbFilePath
fi



sqlite3 $dbFilePath <<< $QUERY
#sqlite3 "/usr/share/nova/database.db" <<< "INSERT INTO credentials VALUES('nova', '\$4\$nova\$h36yyW3noGPSWnx5JCalQCPoo74\$');"

chgrp nova $dbFilePath
chmod g+rw $dbFilePath

echo "SQL schema has been set up for nova."
